# نام کلی این گردش کار (Workflow)
name: Android Build

# تعیین می‌کند که این گردش کار چه زمانی باید اجرا شود
on:
  push:
    branches: [ "main" ]

# تعریف وظایف (Jobs) که باید انجام شوند
jobs:
  build:
    # تعیین سیستم عاملی که این وظیفه روی آن اجرا می‌شود
    runs-on: ubuntu-latest

    # مراحل اجرایی این وظیفه
    steps:
      # مرحله 1: دریافت کدها
      - name: Checkout repository
        uses: actions/checkout@v4

      # مرحله 2: نصب جاوا (JDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # مرحله 3: دادن دسترسی اجرایی به گریدل
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # مرحله 4: بیلد کردن پروژه
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # مرحله 5: آپلود خروجی (فایل APK)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk